name: Deploy website to S3 bucket and Cloudfront

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      REGION: us-west-1
      SOURCE_DIR: website
      DIST_ID: E2L4CHBLNF8SB4

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.REGION }}

      - name: Sync the S3 bucket with AWS CLI
        run: |
          aws s3 sync --delete ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}

      - name: Invalidate the cache in Cloudfront with AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
